import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {ROOT,DATA_HOME} from '../runtime/paths.mjs';
const output=path.resolve(process.argv[2]||path.join(ROOT,'preview'));
const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'gpt-widget-preview-'));
fs.writeFileSync(path.join(dataDir,'display-mode.json'),JSON.stringify({mode:'api'}));
const env={...process.env,WHALE_DESKTOP_TEST:'1',WHALE_GPT_PREVIEW:'1',WHALE_DESKTOP_VERIFY_DIR:output};
delete env.ELECTRON_RUN_AS_NODE;delete env.WHALE_SURFACE_AUDIT;delete env.WHALE_DESKTOP_AUDIT;
const child=spawn(path.join(DATA_HOME,'desktop-runtime/node_modules/electron/dist/electron.exe'),[path.join(ROOT,'desktop/main.cjs'),'--whale-data='+dataDir],{env,windowsHide:true,stdio:['ignore','ignore','pipe']});
let diagnostic='';child.stderr.on('data',b=>{diagnostic=(diagnostic+b).slice(-3000);});
const timeout=setTimeout(()=>child.kill(),45000);
const [code]=await once(child,'close');clearTimeout(timeout);
const reportFile=path.join(output,'gpt-preview.json');
const report=fs.existsSync(reportFile)?JSON.parse(fs.readFileSync(reportFile,'utf8')):{ok:false,error:diagnostic};
assert.equal(code,0,JSON.stringify(report));assert.equal(report.ok,true,JSON.stringify(report));
assert.ok(path.resolve(dataDir).startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(dataDir).startsWith('gpt-widget-preview-'));
fs.rmSync(dataDir,{recursive:true,force:true});
console.log(JSON.stringify(report));
